### ISSUE TITLE
try.csv.gz has empty columns header name

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/otn-taxon-trait-summary#1]
hey @bmaitner - can you help reformat try.cvs.gz to exclude the row number columns with the empty header? 

The empty column make my tools choke on the try trait db :wink: 

```
$ zcat try.csv.gz | head -n2
"","taxonIdVerbatim","scientificNameVerbatim","traitIdVerbatim","traitNameVerbatim","numberOfRecords","family","accessDate","datasetId","curator"
"1",2,"Abarema adenophora",3111,"Leaf area (in case of compound leaves: leaflet, petiole included)",1,"Fabaceae",2022-08-10,"https://opentraits.org/datasets/try","https://opentraits.org/members/brian-s-maitner"
```

**Comment by jhpoelen** [comment]
hey @bmaitner any chance you could update the try.csv.gz to exclude the first row index column? Was hoping to update traits.csv.gz before the weekend and try.csv.gz is still not included ; (

**Comment by bmaitner** [comment]
Sorry again, @jhpoelen !  Fixed and pushed!

**Comment by jhpoelen** [comment]
@bmaitner no worries and thanks for the fix!
